language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_41.gemfile

sudo: false

notifications:
  hipchat:
    rooms:
      secure: "G+RnSzh4v9XYdNO/zxLq66q2uKRomBJlQtUKFbvvawEMCxpTWkxaVQxK01LIj8TaPzHp7Tege6MRihawkO2DPjK8ygf6tzw3GG+B5EHjfD31yMLPnLL53FEuULGbhGy7851kSwD5z/GsN1e6TbWqLFSJqp3W3FYyOLhxMJ1ZXeg="

script: bundle exec rake spec
