language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile

sudo: false

notifications:
  hipchat:
    rooms:
      secure: "G+RnSzh4v9XYdNO/zxLq66q2uKRomBJlQtUKFbvvawEMCxpTWkxaVQxK01LIj8TaPzHp7Tege6MRihawkO2DPjK8ygf6tzw3GG+B5EHjfD31yMLPnLL53FEuULGbhGy7851kSwD5z/GsN1e6TbWqLFSJqp3W3FYyOLhxMJ1ZXeg="

script: bundle exec rake spec
